apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-srep-dynatrace
  namespace: dynatrace
rules:
# can view dynakubes
- apiGroups:
  - dynatrace.com
  resources:
  - dynakubes
  verbs:
  - list
  - get
  - watch
### END