apiVersion: batch/v1
kind: CronJob
metadata:
  name: osd-legacy-ingress-feature-labeller
  namespace: openshift-config
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Replace
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
                weight: 1
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
          serviceAccountName: osd-legacy-ingress-feature-labeller
          restartPolicy: Never
          containers:
          - name: osd-legacy-ingress-feature-labeller
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
            imagePullPolicy: Always
            args:
            - /usr/bin/python
            - -c
            - |
              import os
              import json

              out = os.popen('oc get clusterdeployment -A -ojson').read()
              cd_json_items = json.loads(out)["items"]

              for item in cd_json_items:
                  labels = item["metadata"]["labels"]
                  namespace = item["metadata"]["namespace"]
                  name = item["metadata"]["name"]
                  print(f'Cluster {name} in namespace {namespace}')
                  if not labels.get("hive.openshift.io/version-major-minor"):
                      print("No hive version label on cluster, exiting")
                      continue

                  if labels.get("hive.openshift.io/version-major-minor") and int(labels["hive.openshift.io/version-major-minor"].split(".")[1]) < 14:
                      print("Version less than v4.14, exiting")
                      continue

                  if labels.get("ext-managed.openshift.io/legacy-ingress-support"):
                      print("ext-managed.openshift.io/legacy-ingress-support label already exists, moving to next cluster")
                      continue
                  else:
                      print("ext-managed.openshift.io/legacy-ingress-support label does not exist and cluster is v4.14 or greater. Labelling as legacy-ingress: false.")
                      cmd = f'oc label clusterdeployment -n {namespace} {name} ext-managed.openshift.io/legacy-ingress-support="false"'
                      print(f"Running {cmd}")

                      out = os.popen(cmd)
                      print(out.read())
