deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchLabels:
    ext-managed.openshift.io/hive-shard: "true"
  matchExpressions:
    - key: api.openshift.com/id
      operator: In
      values:
      - "1dn9fsn53b9vh3m63n8ajr679cslbkhd"
      - "1farlonnersks14ohfp155uoonupr9id"
