apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 90-worker-linked-log
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZS53b3JrbG9hZHMubGlua2VkXQphY3RpdmF0aW9uX2Fubm90YXRpb24gPSAiaW8ua3ViZXJuZXRlcy5jcmktby5MaW5rTG9ncyIgCmFsbG93ZWRfYW5ub3RhdGlvbnMgPSBbICJpby5rdWJlcm5ldGVzLmNyaS1vLkxpbmtMb2dzIiBdCg==
        mode: 420
        overwrite: true
        path: /etc/crio/crio.conf.d/90-linked-log.conf
  osImageURL: ""
