deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.0","4.1","4.2","4.3","4.4","4.5","4.6","4.7","4.8","4.9","4.10","4.11","4.12"]
    - key: hive.openshift.io/version-major-minor-patch
      operator: NotIn
      values: ["4.13.0","4.13.1","4.13.2","4.13.3"]
    - key: api.openshift.com/legal-entity-id
      operator: In
      values: "${{LOG_LINKING_ENTITY_IDS}}"
