policy: 
  destination: "acm-policies"
  complianceType: "mustonlyhave"
  clusterSelectors:
    hypershift.open-cluster-management.io/management-cluster: true
  namespaceSelector:
    matchLabels:
      hypershift.openshift.io/hosted-control-plane: true
