apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logger
  namespace: openshift-scanning
spec:
  selector:
    matchLabels:
      name: logger
  template:
    metadata:
      labels:
        name: logger
    spec:
      containers:
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: LOG_WRITER_URL
          value: http://logger.openshift-scanning.svc:8443/api/log
        - name: SCAN_LOG_FILE
          value: /host/var/log/openshift_managed_malware_scan.log
        - name: POD_LOG_FILE
          value: /host/var/log/openshift_managed_pod_creation.log
        - name: POD_SOCK
          value: "@rpc.pod.sock"
        - name: SCAN_SOCK
          value: "@rpc.scan.sock"
        - name: APP_SECRETS_PATH
          value: "/secrets/api_config.json"
        - name: SA_TOKEN_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: OAPI_URL
          value: "https://openshift.default.svc.cluster.local"
        - name: CV_URL
          value: "/apis/config.openshift.io/v1/clusterversions"
        - name: MIDDLEWARE_LOGGER
          value: "true"
        - name: LISTEN_PORT
          value: "8443"
        - name: TLS_CERT_FILE
          value: /certs/tls.crt
        - name: TLS_KEY_FILE
          value: /certs/tls.key
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/pod-logger@sha256:1743c1dade77a0a70ad72d1c06633554f2f70dcde6ae212558bbeb98c14d66a2
        name: logger
        ports:
        - containerPort: 8443
          name: logger
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - mountPath: /secrets
          name: logger-secrets
        - mountPath: /certs
          name: logger-certs
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: SOCK
          value: "@rpc.pod.sock"
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/log-printer@sha256:348371caccd2e36618ec0eddc313ad393307fd5d04cb28e566f7b98216cf7b43
        name: pod-printer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - env:
        - name: OO_PAUSE_ON_START
          value: "false"
        - name: SOCK
          value: "@rpc.scan.sock"
        - name: OPENSSL_FORCE_FIPS_MODE
          value: "1"
        image: quay.io/app-sre/log-printer@sha256:348371caccd2e36618ec0eddc313ad393307fd5d04cb28e566f7b98216cf7b43
        name: scan-printer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: logger-sa
      tolerations:
      - operator: Exists
      volumes:
      - name: logger-secrets
        secret:
          secretName: logger-secrets
      - name: logger-certs
        secret:
          secretName: loggerservice
