apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-srep-opentelemetry
  namespace: openshift-opentelemetry-operator
rules:
# can view opentelemetry collectors
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  - instrumentations
  verbs:
  - list
  - get
  - watch
### END
